version: '3'
services:
  os:
    image: centos # image auto exposes port 5432 in container
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
    working_dir: /root/centos-install-docker
    volumes:
      - "$HOME/workspace/devops/centos-install-docker:/root/centos-install-docker"
