version: '3'
services:
  appclient:
    image: maven:3.3.9-jdk-8-alpine
    command: ["/bin/bash"]
    stdin_open: true
    tty: true
    volumes:
      - "$IDEA_WORKSPACE/simple-cab:/simple-cab"
  appserver:
    image: maven:3.3.9-jdk-8-alpine
    command: ["java", "-jar", "/simple-cab/out/artifacts/server_jar/server.jar"]
    volumes:
      - "$IDEA_WORKSPACE/simple-cab:/simple-cab"
