version: '3'
services:
  server:
    image: maven:3.3.9-jdk-8-alpine
    command: ["mvn", "spring-boot:run"]
    volumes:
      - "$IDEA_WORKSPACE/simple-cab:/simple-cab"
    ports:
      - "8080:8080"
    working_dir: /simple-cab/server
  client:
    image: maven:3.3.9-jdk-8-alpine
    command: ["/bin/bash"]
    stdin_open: true
    tty: true
    working_dir: /simple-cab/client/target
    volumes:
      - "$IDEA_WORKSPACE/simple-cab:/simple-cab"
