version: '3'
services:
  db:
    image: mysql # image auto exposes port 5432 in container
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: mysql
    restart: always
    volumes:
      - "$IDEA_WORKSPACE/simple-cab/db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/"
