version: '3'
services:
  app:
    image: spacemacs/emacs25:develop
    stdin_open: true
    tty: true
    environment:
      DISPLAY: "${DISPLAY}"
      UNAME: "alex"
      UID: "1000"
      TZ: "+11:00 AEDT"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/machine-id:/etc/machine-id:ro"
      - "/var/run/dbus:/var/run/dbus"
      - "$WORKSPACE:/mnt/workspace"
      - "$EMACS_CONFIG/.spacemacs:/home/emacs/.spacemacs"
      - "$EMACS_CONFIG::/home/emacs/Sync/linuxcfg/emacs"
      - "$HOME/config:/home/emacs/config"
    ports:
      - "8080:8080"
    working_dir: /mnt/workspace
