# https://github.com/binhex/arch-pycharm
version: '3'
services:
  ide:
    image: binhex/arch-pycharm
    environment:
      DISPLAY: "${DISPLAY}"
      PUID: "1000"
      PGID: "1000"
    command: ["/opt/idea/bin/pycharm.sh"]
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/etc/localtime:/etc/localtime:ro"
      - "$HOME/.PycharmCE2017.3/config:/config"
      - "$WORKSPACE:/home/developer/workspace"
      - "$PYCHARM_WORKSPACE:/home/developer/PycharmProjects"
      - "/data:/data"
    ports:
      - "5900:5900"
      - "6080:6080"
